"""SQLAlchemy ORM models for the feedback log.

Three tables:
  drafts               — one row per candidate reply generated by drafter.py
  human_actions        — one row per reviewer decision (approved/edited/rejected/auto_sent)
  confidence_predictions — one row per MLP score (Phase 7 populates this)

Design notes:
- JSON columns (cited_sources, uncertainty_flags, features_json) store lists/dicts as
  JSON text so no migration is needed when the structure changes.
- edit_distance is an integer approximation of how much a human changed the draft text.
  0 = unchanged (approved as-is), larger = more editing.
- The confidence_predictions table is written to in Phase 8 (auto-send router) and used
  as the primary feature source for Phase 7 training. It is empty until Phase 7.
"""
from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ── Drafts ──────────────────────────────────────────────────────────────────


class DraftRow(Base):
    """One candidate reply produced by drafter.py."""

    __tablename__ = "drafts"

    id: Mapped[str] = mapped_column(String(36), primary_key=True)
    thread_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    intent: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    sensitivity: Mapped[str] = mapped_column(String(16), nullable=False)

    draft_text: Mapped[str] = mapped_column(Text, nullable=False)
    cited_sources: Mapped[str] = mapped_column(Text, nullable=False, default="[]")
    uncertainty_flags: Mapped[str] = mapped_column(Text, nullable=False, default="[]")

    confidence_label: Mapped[str] = mapped_column(String(16), nullable=False)
    auto_sendable: Mapped[bool] = mapped_column(Boolean, nullable=False)
    guardrail_triggered: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    model: Mapped[str] = mapped_column(String(64), nullable=False)
    input_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    output_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    cost_usd: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    latency_ms: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    parse_attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=1)

    context_cache_key: Mapped[str | None] = mapped_column(String(64), nullable=True)
    context_snapshot_json: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )

    # Relationships
    human_actions: Mapped[list[HumanActionRow]] = relationship(
        "HumanActionRow", back_populates="draft", cascade="all, delete-orphan"
    )
    confidence_predictions: Mapped[list[ConfidencePredictionRow]] = relationship(
        "ConfidencePredictionRow", back_populates="draft", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Draft id={self.id[:8]} thread={self.thread_id} intent={self.intent} label={self.confidence_label}>"


# ── Human Actions ────────────────────────────────────────────────────────────


class HumanActionRow(Base):
    """One reviewer decision on a draft.

    action values:
      approved   — sent as-is (or auto-sent by agent)
      edited     — human modified the text before sending
      rejected   — draft discarded, human wrote a fresh reply
      auto_sent  — agent sent it automatically (no human in the loop)
    """

    __tablename__ = "human_actions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    draft_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("drafts.id", ondelete="CASCADE"), nullable=False, index=True
    )
    action: Mapped[str] = mapped_column(String(16), nullable=False, index=True)

    # Text actually sent to the customer (None for rejected drafts)
    final_text: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Levenshtein-approximated edit distance between draft_text and final_text.
    # 0 = approved unchanged, None = not applicable (rejected).
    edit_distance: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Username of reviewer, or "agent" for auto-sent actions
    reviewer: Mapped[str | None] = mapped_column(String(64), nullable=True, default="human")

    decided_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )

    # Relationship
    draft: Mapped[DraftRow] = relationship("DraftRow", back_populates="human_actions")

    def __repr__(self) -> str:
        return f"<HumanAction draft={self.draft_id[:8]} action={self.action}>"


# ── Confidence Predictions ───────────────────────────────────────────────────


class ConfidencePredictionRow(Base):
    """One MLP confidence score for a draft.

    Written by the Phase 8 router immediately before deciding whether to
    auto-send. Also written during Phase 6 bootstrap to record what the MLP
    *would have* scored on historical drafts.

    features_json is the serialised feature vector dict keyed by feature name.
    model_version is the checkpoint filename (e.g. "model_v1.pt") so we can
    track which checkpoint produced each score and detect drift.
    """

    __tablename__ = "confidence_predictions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    draft_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("drafts.id", ondelete="CASCADE"), nullable=False, index=True
    )

    features_json: Mapped[str] = mapped_column(Text, nullable=False)
    score: Mapped[float] = mapped_column(Float, nullable=False)
    threshold: Mapped[float] = mapped_column(Float, nullable=False, default=0.90)
    would_auto_send: Mapped[bool] = mapped_column(Boolean, nullable=False)
    model_version: Mapped[str | None] = mapped_column(String(64), nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )

    # Relationship
    draft: Mapped[DraftRow] = relationship(
        "DraftRow", back_populates="confidence_predictions"
    )

    def __repr__(self) -> str:
        return f"<ConfidencePrediction draft={self.draft_id[:8]} score={self.score:.3f}>"
